services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host 
    environment:
      - PUID=1000         
      - PGID=1000          
      - VERSION=docker     
    volumes:
      - /:/media   # seus arquivos de mídia
      - ./config:/config           
      - /tmp:/transcode             
    restart: unless-stopped
